#!/usr/bin/env python3
"""Helper for scripts/ban-ip.sh list — prints the ip_bans.db contents.

Formats
-------
    pretty  Human-readable summary (default).
    sql     Paste-ready INSERT statements for a DB with the same schema.
    python  Standalone Python script that (re)creates the full DB from
            scratch, schema + data. Run it like:
                python3 create_bans.py [target.db]

Usage
-----
    python3 _export_bans.py <ip_bans.db path> <format>
"""
from __future__ import annotations

import os
import sqlite3
import sys
from time import time


# ─── SQL schema (kept in sync with ip_ban.py) ─────────────────────────────
SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS active_bans (
        ip          TEXT PRIMARY KEY,
        expires_at  REAL NOT NULL,
        jail        TEXT NOT NULL,
        banned_at   REAL NOT NULL,
        ban_count   INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ban_history (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        ip          TEXT    NOT NULL,
        jail        TEXT    NOT NULL,
        banned_at   REAL    NOT NULL,
        expires_at  REAL    NOT NULL,
        ban_count   INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS blacklist (
        ip          TEXT PRIMARY KEY,
        reason      TEXT NOT NULL DEFAULT '',
        added_at    REAL NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_bh_ip ON ban_history(ip)",
    "CREATE INDEX IF NOT EXISTS idx_bh_ts ON ban_history(banned_at)",
]


def _q(value) -> str:
    """Quote *value* as a single-quoted SQL literal."""
    return "'" + str(value).replace("'", "''") + "'"


def _load(db_path: str):
    now = time()
    if not os.path.exists(db_path):
        return [], [], now

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        bl_rows = conn.execute(
            "SELECT ip, reason, added_at FROM blacklist ORDER BY added_at"
        ).fetchall()
    except sqlite3.OperationalError:
        bl_rows = []
    try:
        ban_rows = conn.execute(
            "SELECT ip, expires_at, jail, banned_at, ban_count"
            " FROM active_bans WHERE expires_at > ? ORDER BY expires_at",
            (now,),
        ).fetchall()
    except sqlite3.OperationalError:
        ban_rows = []
    conn.close()

    blacklist = [
        (r["ip"], (r["reason"] or ""), float(r["added_at"] or 0))
        for r in bl_rows
    ]
    active = [
        (
            r["ip"],
            float(r["expires_at"] or 0),
            r["jail"] or "manual",
            float(r["banned_at"] or 0),
            int(r["ban_count"] or 1),
        )
        for r in ban_rows
    ]
    return blacklist, active, now


def _print_pretty(blacklist, active, now):
    if not blacklist and not active:
        print("  No active bans or blacklisted IPs.")
        return
    if blacklist:
        print(f"  Blacklisted ({len(blacklist)}):")
        for ip, reason, _added_at in blacklist:
            print(f"    ● {ip:>15}  {reason or '–'}")
    if active:
        print(f"  Temp-banned ({len(active)}):")
        for ip, expires_at, jail, _banned_at, _count in sorted(
            active, key=lambda e: e[1] - now
        ):
            r = max(0, int(expires_at - now))
            m, s = divmod(r, 60)
            h, m = divmod(m, 60)
            print(f"    ○ {ip:>15}  {h}h {m}m {s}s left  ({jail})")


def _print_sql(blacklist, active):
    print("-- ip_bans.db dump (paste into sqlite3 target.db)")
    print("BEGIN TRANSACTION;")
    if blacklist:
        print(f"-- {len(blacklist)} blacklist entries")
        for ip, reason, added_at in blacklist:
            print(
                "INSERT OR REPLACE INTO blacklist (ip, reason, added_at) VALUES ("
                f"{_q(ip)}, {_q(reason)}, {added_at!r});"
            )
    if active:
        print(f"-- {len(active)} active temp bans")
        for ip, expires_at, jail, banned_at, count in active:
            print(
                "INSERT OR REPLACE INTO active_bans"
                " (ip, expires_at, jail, banned_at, ban_count) VALUES ("
                f"{_q(ip)}, {expires_at!r}, {_q(jail)}, {banned_at!r}, {int(count)});"
            )
    if not blacklist and not active:
        print("-- (nothing to dump)")
    print("COMMIT;")


# ─── Python-script output ─────────────────────────────────────────────────

_PY_HEADER = '''\
#!/usr/bin/env python3
"""Auto-generated by ban-ip.sh list python.

Creates an ip_bans.db (schema + data) from scratch. Safe to re-run:
uses CREATE TABLE IF NOT EXISTS and INSERT OR REPLACE.

Usage:
    python3 {name} [target_db_path]

If no path is given, writes to ./ip_bans.db in the current directory.
"""
import os
import sqlite3
import sys
'''

_PY_BODY = '''\

SCHEMA_STATEMENTS = [
{schema}
]

BLACKLIST = [
{blacklist}
]

ACTIVE_BANS = [
{active}
]


def main() -> int:
    target = sys.argv[1] if len(sys.argv) > 1 else "ip_bans.db"
    os.makedirs(os.path.dirname(os.path.abspath(target)) or ".", exist_ok=True)

    conn = sqlite3.connect(target)
    try:
        for stmt in SCHEMA_STATEMENTS:
            conn.execute(stmt)
        conn.executemany(
            "INSERT OR REPLACE INTO blacklist (ip, reason, added_at)"
            " VALUES (?, ?, ?)",
            BLACKLIST,
        )
        conn.executemany(
            "INSERT OR REPLACE INTO active_bans"
            " (ip, expires_at, jail, banned_at, ban_count)"
            " VALUES (?, ?, ?, ?, ?)",
            ACTIVE_BANS,
        )
        conn.commit()
    finally:
        conn.close()

    print(
        f"  [ok] Wrote {{len(BLACKLIST)}} blacklist + {{len(ACTIVE_BANS)}}"
        f" active-ban rows to {{target}}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _print_python(blacklist, active):
    schema_lines = ",\n".join("    " + repr(s) for s in SCHEMA_STATEMENTS)
    blacklist_lines = "\n".join("    " + repr(r) + "," for r in blacklist) or "    # (empty)"
    active_lines = "\n".join("    " + repr(r) + "," for r in active) or "    # (empty)"

    sys.stdout.write(_PY_HEADER.format(name="create_bans.py"))
    sys.stdout.write(
        _PY_BODY.format(
            schema=schema_lines,
            blacklist=blacklist_lines,
            active=active_lines,
        )
    )


HELP_TEXT = """\
Usage: _export_bans.py <ip_bans.db> <pretty|sql|python>

Helper for scripts/ban-ip.sh list — prints the ip_bans.db contents.

Arguments:
  <ip_bans.db>    Path to the ip_bans.db SQLite file.
  <format>        Output format. One of:
                    pretty  Human-readable summary (default used by ban-ip.sh).
                    sql     Paste-ready INSERT statements for a matching DB.
                    python  Standalone Python script that (re)creates the DB.

Options:
  -h, --help      Show this help message and exit.
"""


def main() -> int:
    if any(arg in ("-h", "--help") for arg in sys.argv[1:]):
        print(HELP_TEXT)
        return 0
    if len(sys.argv) != 3:
        print("Usage: _export_bans.py <ip_bans.db> <pretty|sql|python>", file=sys.stderr)
        print("Run '_export_bans.py --help' for more information.", file=sys.stderr)
        return 2
    db_path, fmt = sys.argv[1], sys.argv[2]
    blacklist, active, now = _load(db_path)

    if fmt == "pretty":
        if not os.path.exists(db_path):
            print("  No ip_bans.db found.")
            return 0
        _print_pretty(blacklist, active, now)
    elif fmt == "sql":
        _print_sql(blacklist, active)
    elif fmt == "python":
        _print_python(blacklist, active)
    else:
        print(f"  Unknown format: {fmt} (use: pretty, sql, python)", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
